#!/bin/bash
# Copyright (c) 2024 Advanced Micro Devices, Inc. All rights reserved.
set -e

if [ -z $1 ]
then
  install_path=~/rocshmem
else
  install_path=$1
fi

src_path=$(dirname "$(realpath $0)")/../../

cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$install_path \
    -DCMAKE_VERBOSE_MAKEFILE=OFF \
    -DDEBUG=OFF \
    -DPROFILE=OFF \
    -DUSE_GPU_IB=OFF \
    -DUSE_DC=OFF \
    -DUSE_COHERENT_HEAP=ON \
    -DUSE_MANAGED_HEAP=OFF \
    -DUSE_RO=ON \
    -DUSE_IPC=OFF \
    -DUSE_THREADS=ON \
    -DUSE_WF_COAL=OFF \
    $src_path
cmake --build . --parallel 8
cmake --install .
